---
title: "hw"
output: github_document
---

# Download the data

```{r}
github <- "https://github.com/ucb-stat133/stat133-fall-2017/raw/master/"
file <- "data/nba2017-player-statistics.csv"
csv <- paste0(github, file)
download.file(url = csv, destfile = 'nba2017-player-statistics.csv')
```

#Import the data in R

```{r}
library("readr")
library("ggplot2")
library("lattice")

data_by_base<-read.csv("./data/nba2017-player-statistics.csv",header = TRUE)
str(data_by_base)

data_by_readr<-read_csv("./data/nba2017-player-statistics.csv")
str(data_by_readr)
```

##Right after importing the data

```{r}
i<-1
data_by_base$Experience<-as.character(data_by_base$Experience)
while(i<(length(data_by_base$Experience)+1)){
    if(data_by_base$Experience[i]=='R'){
      data_by_base$Experience[i]='0'
    }
    i<-i+1
}
data_by_base$Experience<-as.integer(data_by_base$Experience)
cat(sep="", "the type of Experience is:",typeof(data_by_base$Experience),"\n")
```

## Performance of players

```{r}
data_by_base$Missed_FG<-data_by_base$FGA-data_by_base$FGM
data_by_base$Missed_FT<-data_by_base$FTA-data_by_base$FTM
data_by_base$PTS<-data_by_base$FTM+2*data_by_base$Points2+3*data_by_base$Points3
data_by_base$REB<-data_by_base$OREB+data_by_base$DREB
data_by_base$MPG<-data_by_base$MIN/data_by_base$GP

data_by_base$EFF<- (data_by_base$PTS + data_by_base$REB + data_by_base$AST + 
                    data_by_base$STL + data_by_base$BLK - data_by_base$Missed_FG -                         data_by_base$Missed_FT - data_by_base$TO)/data_by_base$GP

summary(data_by_base$EFF)

hist(data_by_base$EFF,main=('Histogram of Efficiency (EFF)'),col="darkmagenta")

high_EFF<-subset(data_by_base,select = c('Player','Team','Salary','EFF'))
high_EFF<-high_EFF[order(high_EFF$EFF,decreasing = TRUE),]
top_ten<-high_EFF[1:10,]
top_ten
```

```{r}
negative_EFF<-subset(data_by_base,data_by_base$EFF<0)
as.character(negative_EFF$Player)

j<-1
cor_value<-c()
var_name<-c('PTS','REB','AST','STL','BLK','Missed_FG','Missed_FT','TO')
while(j<(length(var_name)+1)){
  if(j>5){
    temp<-(-cor(data_by_base$EFF,data_by_base[var_name[j]]))
  }
  else{
    temp<-(cor(data_by_base$EFF,data_by_base[var_name[j]]))
  }
  cor_value<-c(cor_value,temp)
  j<-j+1
}

cor_result<-data.frame(var_name=var_name,cor_value=cor_value) 


cor_result<-cor_result[order(cor_result$cor_value,decreasing = TRUE),]
cor_result$var_name<-factor(cor_result$var_name)
cor_result

cor_result$label<-(cor_value>0)
ggplot(cor_result,aes(x=reorder(var_name,-cor_value),cor_value,fill=label))+
    geom_bar(stat="identity")+theme(legend.position="none")
```

## Efficiency and Salary

```{r}
data_by_base$Salary<-data_by_base$Salary/1000000
plot(data_by_base$EFF,data_by_base$Salary,xlab = 'EFF',ylab = 'Salary',main = "Scatterplot of EFF and Salary",cex=1,pch=19)
lines(lowess(data_by_base$EFF,data_by_base$Salary), col ='red',lwd=3)
```

```{r}
cat(sep="","the coefficient between EFF and salary is:",
    cor(data_by_base$EFF,data_by_base$Salary),"\n")
```

We can see that the higher the EFF, the higher the wages.
```{r}
players2<-subset(data_by_base,data_by_base$MPG>20)
plot(players2$EFF,players2$Salary,xlab = 'EFF',ylab = 'Salary',main = "players2's Scatterplot of EFF and Salary",cex=1,pch=19)
lines(lowess(players2$EFF,players2$Salary), col ='red',lwd=3)
```

```{r}
cat(sep="","the players2's coefficient between EFF and salary is:",
    cor(players2$EFF,players2$Salary),"\n")
```

